kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:coredns
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterroles/system%3Acoredns
  uid: e64e2c26-6693-4d2d-a8a7-1a65beaf6cfd
  resourceVersion: '380'
  creationTimestamp: '2020-11-09T20:19:47Z'
  managedFields:
    - manager: kubeadm
      operation: Update
      apiVersion: rbac.authorization.k8s.io/v1
      time: '2020-11-09T20:19:47Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:rules: {}
rules:
  - verbs:
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - endpoints
      - services
      - pods
      - namespaces
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - nodes
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:coredns
  creationTimestamp: null
subjects:
  - kind: ServiceAccount
    name: coredns
    namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:coredns
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: coredns
  namespace: kube-system
  creationTimestamp: null

