kind: ServiceAccount
apiVersion: v1
metadata:
  name: kube-proxy
  namespace: kube-system
  creationTimestamp: null
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeadm:node-proxier
  creationTimestamp: null
subjects:
  - kind: ServiceAccount
    name: kube-proxy
    namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:node-proxier
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-proxy
  namespace: kube-system
  creationTimestamp: null
rules:
  - verbs:
      - get
    apiGroups:
      - ''
    resources:
      - configmaps
    resourceNames:
      - kube-proxy
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kube-proxy
  namespace: kube-system
  creationTimestamp: null
subjects:
  - kind: Group
    name: system:bootstrappers:kubeadm:default-node-token
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-proxy
