controlPlaneEndpoint:

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  # storageClassName: default
  annotations: {}
  finalizers:
    - kubernetes.io/pvc-protection

etcd:
  image:
    repository: k8s.gcr.io/etcd
    tag: 3.4.3-0
    PullPolicy: IfNotPresent
    PullSecrets: []
  replicaCount: 3
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
  extraArgs: {}

  ports:
    client: 2379
    peer: 2380
    metrics: 2381
  service:
    ports:
      client: 2379
      peer: 2380
      metrics: 2381

apiserver:
  image:
    repository: k8s.gcr.io/kube-apiserver
    tag: v1.18.2
    PullPolicy: IfNotPresent
    PullSecrets: []
  serviceClusterIPRange: 10.96.0.0/12
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    # limits:
    #   cpu: 100m
    #   memory: 128Mi

  certSANs:
    dnsNames: []
    ipAddresses: []

  extraArgs: {}

  port: 6443
  service:
    enabled: true
    port: 6443

controllerManager:
  image:
    repository: k8s.gcr.io/kube-controller-manager
    tag: v1.18.2
    PullPolicy: IfNotPresent
    PullSecrets: []
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
  extraArgs: {}

  port: 10257
  service:
    enabled: true
    port: 10257

scheduler:
  image:
    repository: k8s.gcr.io/kube-scheduler
    tag: v1.18.2
    PullPolicy: IfNotPresent
    PullSecrets: []
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
  extraArgs: {}

  port: 10259
  service:
    enabled: true
    port: 10259

admin:
  image:
    repository: docker.io/kvaps/kubernetes-tools
    tag: v0.0.1
    PullPolicy: IfNotPresent
    PullSecrets: []
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
