{{- $fullName := include "kubernetes.fullname" . -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-apiserver
  labels:
    app: {{ $fullName }}-apiserver
spec:
  type: NodePort
  publishNotReadyAddresses: true
  ports:
  - port: 6443
    name: client
  selector:
    app: {{ $fullName }}-apiserver
