{{- $fullName := include "kubernetes.fullname" . -}}
{{- if .Values.controllerManager.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-controller-manager
  labels:
    app: {{ $fullName }}-controller-manager
spec:
  type: {{ .Values.controllerManager.service.type }}
  ports:
  - port: {{ .Values.controllerManager.service.port }}
    name: client
    {{- with .Values.controllerManager.service.nodePort }}
    nodePort: {{ . }}
    {{- end }}
  selector:
    app: {{ $fullName }}-controller-manager
{{- end }}
