{{- if .Values.konnectivityServer.enabled }}
{{- $fullName := include "kubernetes.fullname" . -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}-konnectivity-server-conf
data:
  konnectivity-server.conf: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority: /pki/konnectivity-server-client/ca.crt
        server: https://{{ $fullName }}-apiserver:{{ .Values.apiServer.service.port }}
      name: default-cluster
    contexts:
    - context:
        cluster: default-cluster
        namespace: default
        user: default-auth
      name: default-context
    current-context: default-context
    kind: Config
    preferences: {}
    users:
    - name: default-auth
      user:
        client-certificate: /pki/konnectivity-server-client/tls.crt
        client-key: /pki/konnectivity-server-client/tls.key
{{- end }}
