{{- if .Values.admin.job.enabled }}
{{- $fullName := include "kubernetes.fullname" . -}}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ $fullName }}-kubeadm-tasks"
  labels:
    app: "{{ $fullName }}-kubeadm-tasks"
    {{- with .Values.admin.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    checksum/config: {{ include (print $.Template.BasePath "/kubeadm-config.yaml") . | sha256sum }}
    checksum/scripts: {{ include (print $.Template.BasePath "/kubeadm-scripts.yaml") . | sha256sum }}
    {{- with .Values.admin.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  template:
    metadata:
      labels:
        app: "{{ $fullName }}-kubeadm-tasks"
        {{- with .Values.admin.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.admin.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.admin.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.admin.tolerations }}
      tolerations:
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.admin.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.admin.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 10 }}
      {{- end }}
      automountServiceAccountToken: false
      restartPolicy: OnFailure
      containers:
      - name: kubeadm
        {{- with .Values.admin.image }}
        image: "{{ .repository }}{{ if .digest }}@{{ .digest }}{{ else }}:{{ .tag }}{{ end }}"
        imagePullPolicy: {{ .pullPolicy }}
        {{- end }}
        command: [ '/scripts/configure-cluster.sh' ]
        env:
        - name: KUBECONFIG
          value: "/etc/kubernetes/admin.conf"
        {{- with .Values.admin.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        volumeMounts:
        - mountPath: /etc/kubernetes/
          name: kubeconfig
          readOnly: true
        - mountPath: /pki/admin-client
          name: pki-admin-client
        - mountPath: /scripts
          name: scripts
        {{- if or .Values.extraManifests .Values.konnectivityServer.enabled .Values.konnectivityAgent.enabled }}
        - mountPath: /manifests
          name: manifests
        {{- end }}
        - mountPath: /config
          name: config
        {{- with .Values.admin.extraVolumeMounts }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.admin.sidecars }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      volumes:
      - configMap:
          name: "{{ $fullName }}-admin-conf"
        name: kubeconfig
      - secret:
          secretName: "{{ $fullName }}-pki-admin-client"
        name: pki-admin-client
      - name: scripts
        configMap:
          name: "{{ $fullName }}-kubeadm-scripts"
          defaultMode: 0777
      {{- if or .Values.extraManifests .Values.konnectivityServer.enabled .Values.konnectivityAgent.enabled }}
      - name: manifests
        projected:
          sources:
          {{- if or .Values.extraManifests }}
          - secret:
              name: "{{ $fullName }}-extra-manifests"
          {{- end }}
          {{- if or .Values.konnectivityServer.enabled .Values.konnectivityAgent.enabled }}
          - configMap:
              name: "{{ $fullName }}-konnectivity-manifests"
          {{- end }}
      {{- end }}
      - name: config
        configMap:
          name: "{{ $fullName }}-kubeadm-config"
      {{- with .Values.admin.extraVolumes }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
{{- end }}
