{{- $fullName := include "kubernetes.fullname" . -}}
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: "{{ $fullName }}-pki-front-proxy-ca"
spec:
  commonName: "{{ $fullName }}-pki-front-proxy-ca"
  secretName: "{{ $fullName }}-pki-front-proxy-ca"
  duration: 87600h # 3650d
  renewBefore: 8760h # 365d
  organization:
  - "{{ $fullName }}"
  usages:
  - "signing"
  - "digital signature"
  - "key encipherment"
  - "cert sign"
  isCA: true
  issuerRef:
    name: "{{ $fullName }}-selfsigning-issuer"
    kind: Issuer
---
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: "{{ $fullName }}-pki-front-proxy-ca"
spec:
  ca:
    secretName: "{{ $fullName }}-pki-front-proxy-ca"
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: "{{ $fullName }}-pki-front-proxy-client"
spec:
  commonName: "{{ $fullName }}-pki-front-proxy-client"
  secretName: "{{ $fullName }}-pki-front-proxy-client"
  duration: 8760h # 365d
  renewBefore: 4380h # 178d
  organization:
  - "system:masters"
  usages:
  - "signing"
  - "key encipherment"
  - "client auth"
  issuerRef:
    name: "{{ $fullName }}-pki-front-proxy-ca"
    kind: Issuer
