{{- $fullName := include "kubernetes.fullname" . -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ $fullName }}-scheduler"
  labels:
    app: "{{ $fullName }}-scheduler"
spec:
  replicas: {{ .Values.scheduler.replicaCount }}
  selector:
    matchLabels:
      app: "{{ $fullName }}-scheduler"
  template:
    metadata:
      labels:
        app: "{{ $fullName }}-scheduler"
    spec:
      {{- with .Values.scheduler.image.PullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 10 }}
      {{- end }}
      automountServiceAccountToken: false
      containers:
      - command:
        - kube-scheduler
        - --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
        - --authorization-kubeconfig=/etc/kubernetes/scheduler.conf
        - --bind-address=0.0.0.0
        - --kubeconfig=/etc/kubernetes/scheduler.conf
        - --leader-elect=true
        - --secure-port={{ .Values.scheduler.port }}
        {{- range $key, $value := .Values.scheduler.extraArgs }}
        - --{{ $key }}={{ $value }}
        {{- end }}
        image: {{ .Values.scheduler.image.repository }}:{{ .Values.scheduler.image.tag }}
        imagePullPolicy: {{ .Values.scheduler.image.PullPolicy }}
        livenessProbe:
          failureThreshold: 8
          httpGet:
            path: /healthz
            port: {{ .Values.scheduler.port }}
            scheme: HTTPS
          initialDelaySeconds: 15
          timeoutSeconds: 15
        name: kube-scheduler
        resources:
          {{- toYaml .Values.scheduler.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /etc/kubernetes/
          name: kubeconfig
          readOnly: true
      volumes:
      - secret:
          secretName: "{{ $fullName }}-scheduler-conf"
        name: kubeconfig
