{{- $fullName := include "kubernetes.fullname" . -}}
{{- if .Values.scheduler.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-scheduler
  labels:
    app: {{ $fullName }}-scheduler
spec:
  type: {{ .Values.scheduler.service.type }}
  ports:
  - port: {{ .Values.scheduler.service.port }}
    name: client
    {{- with .Values.scheduler.service.nodePort }}
    nodePort: {{ . }}
    {{- end }}
  selector:
    app: {{ $fullName }}-scheduler
{{- end }}
